version: '3.8'

services:
  backend:
    container_name: prospect_backend
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./python_backend:/app
      - /cloudsql:/cloudsql
    environment:
      - DB_HOST=/cloudsql/cloud-engineer-test-juanc:us-central1:files
      - PORT=8080
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=filesdb
      - DB_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://localhost:4321
    networks:
      - prospect-network

  frontend:
    container_name: prospect_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - prospect-network

networks:
  prospect-network:
    name: prospect-network
    driver: bridge
