version: '3.8'

services:
  backend:
    container_name: prospect_backend
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./python_backend:/app
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=filesdb

  frontend:
    container_name: prospect_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=/api
      - VITE_PUBLIC_API_URL=/api
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: prospect_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
