version: '3.8'

services:
  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.2
    command:
      - "/cloud_sql_proxy"
      - "--instances=cloud-engineer-test-juanc:us-central1:files=tcp:5432"
      - "--credentials=/secrets/cloudsql/credentials.json"
    volumes:
      - ./secrets/cloudsql:/secrets/cloudsql:ro
    # uses the distroless proxy image with IAM & TLS authentication :contentReference[oaicite:0]{index=0}

  backend:
    container_name: prospect_backend
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python_backend:/app
    depends_on:
      - cloudsql-proxy
    environment:
      - DB_HOST=cloudsql-proxy        # service name resolution over Compose network :contentReference[oaicite:1]{index=1}
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=filesdb
      - CORS_ALLOWED_ORIGINS=http://localhost:4321

  frontend:
    container_name: prospect_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  # no external volumes needed for proxy when using TCP
