version: '3.8'

services:
  backend:
    container_name: prospect_backend
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python_backend:/app
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=filesdb
      - PROJECT_ID=cloud-engineer-test-juanc
      - LOCATION=us-central1-a
      - PROCESSOR_ID=1e60d3bd63a0d751

  frontend:
    container_name: prospect_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_PUBLIC_API_URL=/api
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: prospect_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
